# Generated by Django 4.1.13 on 2025-05-09 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talepler', '0002_egitmenbasvurusu'),
        ('kullanicilar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sohbet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('ders_istegi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sohbet_kanali', to='talepler.dersistegi', verbose_name='İlgili Ders İsteği')),
                ('katilimcilar', models.ManyToManyField(related_name='katildigi_sohbetler', to='kullanicilar.kullaniciprofili', verbose_name='Sohbet Katılımcıları')),
            ],
            options={
                'verbose_name': 'Sohbet Kanalı',
                'verbose_name_plural': 'Sohbet Kanalları',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField(verbose_name='Mesaj İçeriği')),
                ('gonderilme_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Tarihi')),
                ('okundu_bilgisi', models.BooleanField(default=False, verbose_name='Okundu Bilgisi')),
                ('gonderen_kullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gonderdigi_mesajlar', to='kullanicilar.kullaniciprofili', verbose_name='Gönderen Kullanıcı')),
                ('sohbet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to='iletisim.sohbet', verbose_name='Sohbet Kanalı')),
            ],
            options={
                'verbose_name': 'Sohbet Mesajı',
                'verbose_name_plural': 'Sohbet Mesajları',
                'ordering': ['gonderilme_tarihi'],
            },
        ),
    ]
