# Generated by Django 4.1.13 on 2025-05-09 23:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talepler', '0002_egitmenbasvurusu'),
        ('kullanicilar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degerlendirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puan', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Verilen Puan (1-5)')),
                ('yorum', models.TextField(blank=True, verbose_name='Yorum')),
                ('degerlendirme_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Değerlendirme Tarihi')),
                ('degerlendiren_kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yaptigi_degerlendirmeler', to='kullanicilar.kullaniciprofili', verbose_name='Değerlendirmeyi Yapan Kullanıcı')),
                ('degerlendirilen_kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aldigi_degerlendirmeler', to='kullanicilar.kullaniciprofili', verbose_name='Değerlendirilen Kullanıcı')),
                ('ders_istegi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degerlendirmeleri', to='talepler.dersistegi', verbose_name='İlgili Ders İsteği')),
            ],
            options={
                'verbose_name': 'Ders Değerlendirmesi',
                'verbose_name_plural': 'Ders Değerlendirmeleri',
                'ordering': ['-degerlendirme_tarihi'],
            },
        ),
        migrations.AddIndex(
            model_name='degerlendirme',
            index=models.Index(fields=['ders_istegi', 'degerlendiren_kullanici'], name='geribildiri_ders_is_250756_idx'),
        ),
        migrations.AddIndex(
            model_name='degerlendirme',
            index=models.Index(fields=['ders_istegi', 'degerlendirilen_kullanici'], name='geribildiri_ders_is_92c55d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='degerlendirme',
            unique_together={('ders_istegi', 'degerlendiren_kullanici', 'degerlendirilen_kullanici')},
        ),
    ]
