# Generated by Django 4.1.13 on 2025-05-09 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KullaniciProfili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universite', models.CharField(blank=True, max_length=200)),
                ('bolum', models.CharField(blank=True, max_length=200)),
                ('profil_fotografi_url', models.URLField(blank=True, help_text="Profil fotoğrafının URL'si", null=True)),
                ('kullanici_rolu', models.CharField(choices=[('NORMAL', 'Normal Kullanıcı'), ('MODERATOR', 'Moderatör'), ('ADMIN', 'Admin')], default='NORMAL', max_length=10)),
                ('ban_durumu', models.BooleanField(default=False)),
                ('ban_bitis_tarihi', models.DateTimeField(blank=True, null=True)),
                ('hakkinda', models.TextField(blank=True)),
                ('genel_bulusma_yontemleri', models.TextField(blank=True, help_text='Tercih edilen genel buluşma yöntemleri/mekanları')),
                ('ders_karsiligi_beklentileri', models.TextField(blank=True, help_text='Ders karşılığında genel beklentiler')),
                ('ogrenmek_istedigi_dersler_aciklama', models.TextField(blank=True, help_text='Öğrenilmek istenen dersler hakkında genel açıklama')),
                ('yetkin_oldugu_dersler_aciklama', models.TextField(blank=True, help_text='Yardımcı olunabilecek dersler hakkında genel açıklama')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
