# Generated by Django 5.2.1 on 2025-05-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullaniciprofili',
            name='kullanici_rolu',
            field=models.CharField(choices=[('NORMAL', 'Normal Kullanıcı'), ('EGITMEN', 'Eğitmen'), ('MODERATOR', 'Moderatör'), ('ADMIN', 'Admin')], default='NORMAL', max_length=10),
        ),
    ]
