# Generated by Django 5.2.1 on 2025-05-25 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0002_alter_kullaniciprofili_kullanici_rolu'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgitmenBasvuruFormu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egitim_bilgileri', models.TextField(help_text='Eğitim geçmişiniz, mezun olduğunuz bölümler veya devam ettiğiniz programlar', verbose_name='Eğitim Bilgileri')),
                ('deneyim', models.TextField(help_text='Eğitmenlik veya öğretim alanındaki deneyimleriniz', verbose_name='Deneyim')),
                ('uzmanlik_alanlari', models.TextField(help_text='Hangi konularda ders verebileceğiniz', verbose_name='Uzmanlık Alanları')),
                ('motivasyon', models.TextField(help_text='Neden eğitmen olmak istiyorsunuz?', verbose_name='Motivasyon')),
                ('basvuru_durumu', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi')], default='BEKLEMEDE', max_length=15, verbose_name='Başvuru Durumu')),
                ('basvuru_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Başvuru Tarihi')),
                ('degerlendirilme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Değerlendirilme Tarihi')),
                ('red_sebebi', models.TextField(blank=True, help_text='Başvuru reddedildiyse, sebebi buraya yazılır', verbose_name='Ret Sebebi')),
                ('degerlendiren_moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degerlendirdigi_egitmen_basvurulari', to='kullanicilar.kullaniciprofili', verbose_name='Değerlendiren Moderatör')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egitmen_basvurulari', to='kullanicilar.kullaniciprofili', verbose_name='Başvuran Kullanıcı')),
            ],
            options={
                'verbose_name': 'Eğitmen Başvuru Formu',
                'verbose_name_plural': 'Eğitmen Başvuru Formları',
                'ordering': ['-basvuru_tarihi'],
            },
        ),
    ]
