# Generated by Django 5.2.1 on 2025-05-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0003_egitmenbasvuruformu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullaniciprofili',
            name='ders_karsiligi_beklentileri',
        ),
        migrations.RemoveField(
            model_name='kullaniciprofili',
            name='genel_bulusma_yontemleri',
        ),
        migrations.RemoveField(
            model_name='kullaniciprofili',
            name='ogrenmek_istedigi_dersler_aciklama',
        ),
        migrations.RemoveField(
            model_name='kullaniciprofili',
            name='yetkin_oldugu_dersler_aciklama',
        ),
    ]
