# Generated by Django 5.2.1 on 2025-05-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0004_remove_kullaniciprofili_ders_karsiligi_beklentileri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullaniciprofili',
            name='profil_fotografi_url',
        ),
        migrations.AddField(
            model_name='kullaniciprofili',
            name='profil_fotografi_index',
            field=models.IntegerField(default=0, help_text='Profil fotoğrafı seçimi (0-6 arası)'),
        ),
    ]
