# Generated by Django 5.2.1 on 2025-05-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0005_remove_kullaniciprofili_profil_fotografi_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullaniciprofili',
            name='sinif',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
