# Generated by Django 4.1.13 on 2025-05-09 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kullanicilar', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Rapor Edilen İçerik ID')),
                ('gerekce', models.TextField(verbose_name='Rapor Gerekçesi')),
                ('durum', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('INCELENDI_ISLEM_YAPILDI', 'İncelendi - İşlem Yapıldı'), ('INCELENDI_GEREK_YOK', 'İncelendi - İşlem Gerekmedi'), ('GECERSIZ', 'Geçersiz Rapor')], default='BEKLEMEDE', max_length=30, verbose_name='Rapor Durumu')),
                ('rapor_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Rapor Tarihi')),
                ('incelenme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='İncelenme Tarihi')),
                ('moderator_notu', models.TextField(blank=True, verbose_name='Moderatör Notu')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Rapor Edilen İçerik Türü')),
                ('inceleyen_moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inceledigi_raporlar', to='kullanicilar.kullaniciprofili', verbose_name='İnceleyen Moderatör')),
                ('rapor_eden_kullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yaptigi_raporlar', to='kullanicilar.kullaniciprofili', verbose_name='Rapor Eden Kullanıcı')),
                ('rapor_edilen_kullanici_profili', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hakkindaki_raporlar', to='kullanicilar.kullaniciprofili', verbose_name='(Varsa) Rapor Edilen Kullanıcı Profili')),
            ],
            options={
                'verbose_name': 'İçerik Raporu',
                'verbose_name_plural': 'İçerik Raporları',
                'ordering': ['-rapor_tarihi'],
            },
        ),
        migrations.AddIndex(
            model_name='rapor',
            index=models.Index(fields=['content_type', 'object_id'], name='moderasyon__content_1b2d90_idx'),
        ),
    ]
