# Generated by Django 4.1.13 on 2025-05-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_adi', models.CharField(max_length=255, unique=True, verbose_name='Ders Adı')),
                ('kategori', models.CharField(blank=True, help_text='Dersin ait olduğu genel kategori (örn: Matematik, Yazılım, Dil)', max_length=100, verbose_name='Kategori')),
                ('aciklama', models.TextField(blank=True, help_text='Ders hakkında kısa bir açıklama', verbose_name='Açıklama')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('aktif_mi', models.BooleanField(default=True, help_text='Bu dersin platformda seçilebilir olup olmadığını belirtir.', verbose_name='Aktif Mi?')),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
                'ordering': ['ders_adi'],
            },
        ),
    ]
