# Generated by Django 4.1.13 on 2025-05-09 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kullanicilar', '0001_initial'),
        ('dersler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DersIstegi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talep_basligi', models.CharField(max_length=255, verbose_name='Talep Başlığı/Özel Konu')),
                ('detayli_aciklama', models.TextField(help_text='Öğrenmek istediğiniz konular, mevcut bilgi seviyeniz ve dersten beklentileriniz.', verbose_name='Detaylı Açıklama')),
                ('beklenen_seviye', models.CharField(choices=[('BASLANGIC', 'Başlangıç'), ('ORTA', 'Orta'), ('ILERI', 'İleri'), ('FARKETMEZ', 'Farketmez')], default='FARKETMEZ', max_length=10, verbose_name='Beklenen Seviye')),
                ('teklif_edilen_karsilik', models.TextField(blank=True, help_text='Ders karşılığında ne teklif ediyorsunuz? (örn: bir kahve, ücret, tatlı, karşılıklı ders vb.)', verbose_name='Teklif Edilen Karşılık')),
                ('mekan_tercihi', models.TextField(blank=True, help_text='Buluşma için tercih ettiğiniz mekan türü (örn: kampüs kütüphanesi, kafe, online vb.)', verbose_name='Mekan Tercihi')),
                ('zaman_tercihi', models.TextField(blank=True, help_text='Ders için uygun olduğunuz genel zaman aralıkları.', verbose_name='Zaman Tercihi')),
                ('talep_durumu', models.CharField(choices=[('AKTIF', 'Aktif'), ('ANLASILDI', 'Anlaşıldı'), ('TAMAMLANDI', 'Tamamlandı'), ('IPTAL_EDILDI', 'İptal Edildi'), ('SURESI_DOLDU', 'Süresi Doldu')], default='AKTIF', max_length=15, verbose_name='Talebin Durumu')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('ders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ders_istekleri', to='dersler.ders', verbose_name='İlgili Standart Ders')),
                ('talep_eden_kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ders_istekleri', to='kullanicilar.kullaniciprofili', verbose_name='Talep Eden Kullanıcı')),
            ],
            options={
                'verbose_name': 'Ders İsteği',
                'verbose_name_plural': 'Ders İstekleri',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
    ]
