# Generated by Django 4.1.13 on 2025-05-09 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0001_initial'),
        ('talepler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgitmenBasvurusu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basvuru_mesaji', models.TextField(blank=True, help_text='Neden yardımcı olabileceğinize dair kısa bir açıklama.', verbose_name='Başvuru Mesajı')),
                ('basvuru_durumu', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('KABUL_EDILDI', 'Kabul Edildi'), ('REDDEDILDI', 'Reddedildi'), ('GERI_CEKILDI', 'Geri Çekildi')], default='BEKLEMEDE', max_length=15, verbose_name='Başvuru Durumu')),
                ('basvuru_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Başvuru Tarihi')),
                ('basvuran_egitmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yaptigi_egitmen_basvurulari', to='kullanicilar.kullaniciprofili', verbose_name='Başvuran Eğitmen')),
                ('ders_istegi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egitmen_basvurulari', to='talepler.dersistegi', verbose_name='Ders İsteği')),
            ],
            options={
                'verbose_name': 'Eğitmen Başvurusu',
                'verbose_name_plural': 'Eğitmen Başvuruları',
                'ordering': ['-basvuru_tarihi'],
                'unique_together': {('ders_istegi', 'basvuran_egitmen')},
            },
        ),
    ]
