# Generated by Django 4.1.13 on 2025-05-10 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0001_initial'),
        ('talepler', '0002_egitmenbasvurusu'),
    ]

    operations = [
        migrations.AddField(
            model_name='dersistegi',
            name='atanan_egitmen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verdigi_dersler', to='kullanicilar.kullaniciprofili', verbose_name='Atanan Eğitmen'),
        ),
        migrations.AlterField(
            model_name='dersistegi',
            name='talep_durumu',
            field=models.CharField(choices=[('AKTIF', 'Aktif'), ('EGITMEN_ATANDI', 'Eğitmen Atandı'), ('TAMAMLANDI', 'Tamamlandı'), ('KAPALI', 'Kapalı')], default='AKTIF', max_length=20, verbose_name='Talebin Durumu'),
        ),
    ]
