# Generated by Django 5.2.1 on 2025-05-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talepler', '0003_dersistegi_atanan_egitmen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dersistegi',
            name='egitmen_tamamlama_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Eğitmen Tamamlama Tarihi'),
        ),
        migrations.AddField(
            model_name='dersistegi',
            name='ogrenci_tamamlama_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Öğrenci Tamamlama Tarihi'),
        ),
        migrations.AlterField(
            model_name='dersistegi',
            name='talep_durumu',
            field=models.CharField(choices=[('AKTIF', 'Aktif'), ('EGITMEN_ATANDI', 'Eğitmen Atandı'), ('OGRENCI_TAMAMLADI', 'Öğrenci Tamamladı'), ('EGITMEN_TAMAMLADI', 'Eğitmen Tamamladı'), ('TAMAMLANDI', 'Tamamlandı'), ('KAPALI', 'Kapalı')], default='AKTIF', max_length=20, verbose_name='Talebin Durumu'),
        ),
    ]
