# Generated by Django 5.2.1 on 2025-05-26 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0004_remove_kullaniciprofili_ders_karsiligi_beklentileri_and_more'),
        ('talepler', '0004_dersistegi_egitmen_tamamlama_tarihi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dersistegi',
            name='atanan_egitmen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atanan_ders_istekleri', to='kullanicilar.kullaniciprofili', verbose_name='Atanan Eğitmen'),
        ),
    ]
